### PR TITLE
Initial framework for uhura functional automation

### PR DESCRIPTION
**Pull request by fonzi**
@dukex Here is the initial set up for functional testing with Cucumber Selenium in Ruby. At the moment it is not much, expect a failure login test. Checking for the element to appear. 

I attached a README.md at tests/functional/README.md

Feel free to pull this to your local branch, and give it a run. You will need firefox. I used firefox 38 on linux, however this should work on any system that has ruby/bundle installed along with the gems.

### CODE REVIEW

**Comment by dukex** [comment]
@fonzi great job! 
We need put this tests to run in travis CI.

**Comment by fonzi** [comment]
@dukex Cool, how is that done? I've never used travis before. Nor does it look like any CI tool I've used before.

**Comment by dukex** [comment]
We need config the .travis.yml as recommend here -> http://docs.travis-ci.com/user/gui-and-headless-browsers/

I don't understand one thing, how cucumber tests will create a correct scenario to make tests. With correct scenario I mean create a valid user, channels, episodes, etc. Using ember-cli acceptance test with ember-cli-mirage we can make it easy, like the example https://github.com/uhuraapp/uhura-frontend/blob/master/tests/acceptance/player-test.js#L30-L31

**Comment by fonzi** [comment]
@dukex Thanks for the traver.yml link. 

Cucumber is only the front end of the test, so it can be read easily. Ruby will create all of the channels and such using selenium, once the functionality of searching is on the app. This type of testing, is only UI testing. Although API calls could also be made if we wish. But I think the JS you already have in place takes care of the API testing.

A downside which I forgot to mention about this is that this type of testing can be fragile when major overhauls happens to the front end UI, 

Example if we decide to change the UI from the current one and do not keep the ID's in place test will begin to fail, of if the CSS structure changes.

**Comment by dukex** [comment]
Hi @fonzi 
I'll accept it so you can work on tests in master branch

**Pull request merged**
