### PR TITLE
Registration Flow, Closes #107

### LINKED ISSUE #107: Register
As a unauthenticated user
To use Uhura 
I want create a account

Given I'm on register page
When I fill the name field with 'Duke'
And I fill the email field with 'x@com'
And I fill the password with 'xx'
Then I need see a welcome message

Given I'm on register page
When I fill the name field with 'Duke'
And I fill the email field with 'x@com'
Then I need see a error about password is required

Given I'm on register page
When I click on 'Sign in with google'
And I accept the oauth flow
Then I need see a welcome massage

Given I'm o register page
When I click on 'sign with google'
And I denied the oauth flow 
Then I need see a error about denied ouath flow

### PR DESCRIPTION
**Pull request by dukex**
- [x] Sign Up form 
- [x] handle with blank field 
- [x] handle with sort password
- [x] handle with server error 
- [x] better notification messages for users

### CODE REVIEW

**Comment by dukex** [comment]
Hi @fonzi 
You can validate the register flow?
I need add better error messages, if you have some suggestion tell me.

To test this feature use email with 'test' prefix like 'test.user1@domain.com' so after I'll delete this users

**Comment by fonzi** [comment]
Sure. I'll take a look. And report back.

**Comment by dukex** [comment]
Thanks @fonzi 
When you finish the tests please merge this branch

**Comment by fonzi** [comment]
Everything looks good. Merging the branch to master.

**Pull request merged**
